import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { Anthropic } from "@anthropic-ai/sdk";

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

// Public route - no auth required
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const { answers, participantName } = await req.json();

    if (!participantName || !participantName.trim()) {
      return NextResponse.json(
        { error: "Participant name is required" },
        { status: 400 }
      );
    }

    // 1. Fetch the assessment with ideal answers
    const assessment = await prisma.freeAssessment.findUnique({
      where: { id, isActive: true },
    });

    if (!assessment) {
      return NextResponse.json({ error: "Assessment not found" }, { status: 404 });
    }

    const questions = assessment.questions as Array<{
      question: string;
      idealAnswer: string;
    }>;

    // 2. Construct prompt for AI Grading
    let prompt = `You are an expert academic grader prioritizing conceptual understanding. 
Your task is to evaluate a person's answers to an open-ended assessment.
For each question, determine if the answer correctly captures the core concept of the Ideal Answer.
Do not penalize for different wording or sentence structure if the meaning is correct.
Focus on whether the person understands the topic.

Also, analyze if the person's answer appears to be generated by an AI. Look for:
- Robotic or overly formal phrasing
- Typical AI structure (intro, bullet points, conclusion) where not requested
- Common AI words like "delve", "tapestry", "landscape", "crucial" used excessively
- Perfect grammar but lacking personal nuance

Here are the questions and answers:
`;

    questions.forEach((q, index) => {
      const studentAnswer = answers[index] || "No answer provided.";
      prompt += `
Question ${index + 1}: ${q.question}
Ideal Answer: ${q.idealAnswer}
Participant Answer: ${studentAnswer}
-----------------------------------
`;
    });

    prompt += `
Provide your output as a valid JSON object with the following structure:
{
  "questionResults": [
    {
      "questionIndex": number,
      "score": number (0-100),
      "feedback": "Brief feedback explaining the score in Spanish",
      "suspectedAI": boolean (true if the answer looks like it was generated by an AI),
      "aiSuspicionReason": "Reason for suspicion if suspectedAI is true, else null"
    }
  ],
  "overallFeedback": "Overall summary of the person's performance in Spanish",
  "overallScore": number (average of question scores)
}

Do not include any markdown formatting or explanation outside the JSON. Just the JSON string.`;

    // 3. Call AI
    const response = await anthropic.messages.create({
      model: "claude-3-haiku-20240307",
      max_tokens: 2000,
      messages: [{ role: "user", content: prompt }],
    });

    const aiResponseText = (response.content[0] as any).text;

    // Clean up response if it contains markdown code blocks
    const cleanJson = aiResponseText.replace(/```json\n?|\n?```/g, "").trim();

    let gradingResult;
    try {
      gradingResult = JSON.parse(cleanJson);
    } catch (e) {
      console.error("Failed to parse AI response:", aiResponseText);
      return NextResponse.json({ error: "Grading failed" }, { status: 500 });
    }

    const finalScore = Math.round(gradingResult.overallScore);
    const passed = finalScore >= assessment.passingScore;

    // 4. Save Attempt
    const attempt = await prisma.freeAssessmentAttempt.create({
      data: {
        assessmentId: id,
        participantName: participantName.trim(),
        score: finalScore,
        passed,
        answers: {
          rawAnswers: answers,
          grading: gradingResult,
        },
      },
    });

    return NextResponse.json({
      score: finalScore,
      passed,
      feedback: gradingResult.overallFeedback,
      details: gradingResult.questionResults,
      passingScore: assessment.passingScore,
    });
  } catch (error) {
    console.error("Error submitting assessment:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
