import { Anthropic } from "@anthropic-ai/sdk";

interface GradingResult {
  score: number;
  feedback: string;
  aiScore: number; // Likelihood that the answer was generated by AI (0-100)
  aiReasoning: string; // Brief reasoning for the AI score (not shown to student)
}

export async function gradeAnswer(
  question: string,
  studentAnswer: string,
  idealAnswer: string
): Promise<GradingResult> {
  const anthropic = new Anthropic({
    apiKey: process.env.ANTHROPIC_API_KEY,
  });

  try {
    const systemPrompt = `You are an expert AI grader and detector for an educational platform.
Your task is twofold:
1. Evaluate a student's answer based on the instructor's ideal answer.
Assign a score (0-100) and provide constructive feedback for the student.

2. Detect if the student's answer was likely generated by another AI.
Look for common AI patterns:
- Overly structured response (perfect bullet points, balanced paragraphs)
- High degree of robotic politeness or "helpful" tone
- Use of typical LLM phrases ("It is important to note...", "In conclusion...", "Furthermore...")
- Generic phrasing and lack of specific personal insight or "human" stylistic inconsistencies

Question: "${question}"
Ideal Answer / Criteria: "${idealAnswer}"
Student Answer: "${studentAnswer}"

Instructions:
1. Assign a grade score (0-100).
2. Assign an AI likelihood score (0-100), where 100 means definitely generated by AI.
3. Provide feedback for the student.
4. Provide a brief reasoning for the AI score (max 2 sentences, this is for administrators).
5. Return ONLY a JSON object:
{
  "score": number,
  "feedback": "string",
  "aiScore": number,
  "aiReasoning": "string"
}
Do not include any other text.`;

    const response = await anthropic.messages.create({
      model: "claude-3-haiku-20240307",
      max_tokens: 500,
      messages: [{ role: "user", content: "Grade this answer." }],
      system: systemPrompt,
    });

    const text = (response.content[0] as any).text;

    // Clean up potential markdown code blocks if the model adds them
    const jsonString = text.replace(/```json/g, "").replace(/```/g, "").trim();

    return JSON.parse(jsonString);
  } catch (error: any) {
    console.error("AI Grading Error Details:", {
      message: error.message,
      stack: error.stack,
      status: error.status,
      name: error.name
    });
    // Fallback in case of AI failure
    return {
      score: 0,
      feedback: "Error al calificar automáticamente. Se requiere revisión manual.",
      aiScore: 0,
      aiReasoning: "Error en el sistema de detección.",
    };
  }
}
