/**
 * Re-grades the evaluation attempt for a specific user that received score 0
 * due to the deprecated claude-3-haiku-20240307 model.
 *
 * SAFE: Only updates the single EvaluationAttempt record with score=0 for the given email.
 * Run with: npx tsx scripts/regrade-user-attempt.ts
 */
import * as fs from "fs";
import * as path from "path";
import * as readline from "readline";

// Load .env.local manually (no dotenv dependency needed)
const envPath = path.resolve(process.cwd(), ".env.local");
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, "utf-8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex).trim();
    const value = trimmed.slice(eqIndex + 1).trim();
    if (!process.env[key]) process.env[key] = value;
  }
  console.log("✓ Variables cargadas desde .env.local");
} else {
  console.error("❌ No se encontró .env.local");
  process.exit(1);
}

import { PrismaClient } from "@prisma/client";
import { Anthropic } from "@anthropic-ai/sdk";

const prisma = new PrismaClient();
const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const TARGET_EMAIL = "cartera@colegiofontan.edu.co";
const GRADING_MODEL = "claude-haiku-4-5-20251001";

async function gradeAnswers(
  questions: Array<{ question: string; idealAnswer: string }>,
  answers: Record<number, string>
) {
  let prompt = `You are an expert academic grader prioritizing conceptual understanding. 
Your task is to evaluate a student's answers to an open-ended exam.
For each question, determine if the Student Answer correctly captures the core concept of the Ideal Answer.
Do not penalize for different wording or sentence structure if the meaning is correct.
Focus on whether the student understands the topic.

Also, analyze if the student's answer appears to be generated by an AI. Look for:
- Robotic or overly formal phrasing
- Typical AI structure (intro, bullet points, conclusion) where not requested
- Common AI words like "delve", "tapestry", "landscape", "crucial" used excessively
- Perfect grammar but lacking personal nuance

Here are the questions and answers:
`;

  questions.forEach((q, index) => {
    const studentAnswer = answers[index] || "No answer provided.";
    prompt += `
Question ${index + 1}: ${q.question}
Ideal Answer: ${q.idealAnswer}
Student Answer: ${studentAnswer}
-----------------------------------
`;
  });

  prompt += `
Provide your output as a valid JSON object with the following structure:
{
  "questionResults": [
    {
      "questionIndex": number,
      "score": number (0-100),
      "feedback": "Brief feedback explaining the score",
      "suspectedAI": boolean,
      "aiSuspicionReason": "Reason if suspectedAI is true, else null"
    }
  ],
  "overallFeedback": "Overall summary of the student's performance",
  "overallScore": number (average of question scores)
}

Do not include any markdown formatting or explanation outside the JSON.`;

  const response = await anthropic.messages.create({
    model: GRADING_MODEL,
    max_tokens: 8192,
    messages: [{ role: "user", content: prompt }],
  });

  const raw = (response.content[0] as any).text;
  const clean = raw.replace(/```json\n?|\n?```/g, "").trim();
  return JSON.parse(clean);
}

function ask(question: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer);
    });
  });
}

async function main() {
  console.log(`\n🔍 Buscando usuario: ${TARGET_EMAIL}`);
  console.log(`📡 Database: ${process.env.DATABASE_URL?.split("@")[1]?.split("/")[0] ?? "desconocida"}\n`);

  // 1. Find user
  const user = await prisma.user.findUnique({
    where: { email: TARGET_EMAIL },
    select: { id: true, email: true, name: true },
  });

  if (!user) {
    console.error(`❌ Usuario no encontrado: ${TARGET_EMAIL}`);
    await prisma.$disconnect();
    process.exit(1);
  }

  console.log(`✓ Usuario encontrado: ${user.name ?? "(sin nombre)"} (id: ${user.id})`);

  // 2. Find failed attempts (score = 0) for this user
  const failedAttempts = await prisma.evaluationAttempt.findMany({
    where: {
      score: 0,
      enrollment: { userId: user.id },
    },
    include: {
      evaluation: { select: { id: true, passingScore: true, questions: true } },
      enrollment: { include: { course: { select: { title: true } } } },
    },
    orderBy: { completedAt: "desc" },
  });

  if (failedAttempts.length === 0) {
    console.log("ℹ️  No se encontraron intentos con score=0 para este usuario.");
    await prisma.$disconnect();
    return;
  }

  console.log(`\n⚠️  Se encontraron ${failedAttempts.length} intento(s) con score=0:\n`);
  failedAttempts.forEach((a, i) => {
    const rawAnswers = (a.answers as any)?.rawAnswers ?? {};
    const answersCount = Object.keys(rawAnswers).length;
    console.log(`  [${i + 1}] Attempt ID: ${a.id}`);
    console.log(`       Curso: ${a.enrollment.course.title}`);
    console.log(`       Fecha: ${a.completedAt?.toLocaleString("es-CO") ?? "sin fecha"}`);
    console.log(`       Respuestas guardadas: ${answersCount}`);
    console.log(`       Passing score: ${a.evaluation.passingScore}`);
    console.log();
  });

  if (failedAttempts.length > 1) {
    console.log("Hay más de un intento fallido. Se re-calificarán TODOS los que tienen score=0.");
    console.log("Si solo quieres uno específico, cancela y ajusta el script.\n");
  }

  // 3. Show what would be re-graded
  const confirm = await ask("¿Confirmas que quieres re-calificar estos intentos? (escribe 'si' para continuar): ");
  if (confirm.trim().toLowerCase() !== "si") {
    console.log("Operación cancelada.");
    await prisma.$disconnect();
    return;
  }

  // 4. Re-grade each failed attempt
  for (const attempt of failedAttempts) {
    console.log(`\n⏳ Re-calificando attempt ${attempt.id}...`);

    const rawAnswers = (attempt.answers as any)?.rawAnswers ?? {};
    const questions = attempt.evaluation.questions as Array<{
      question: string;
      idealAnswer: string;
    }>;

    if (Object.keys(rawAnswers).length === 0) {
      console.log(`  ⚠️  Sin rawAnswers guardadas — saltando.`);
      continue;
    }

    let gradingResult;
    try {
      gradingResult = await gradeAnswers(questions, rawAnswers);
    } catch (err) {
      console.error(`  ❌ Error al calificar:`, err);
      continue;
    }

    const newScore = Math.round(gradingResult.overallScore);
    const newPassed = newScore >= attempt.evaluation.passingScore;

    console.log(`  → Nuevo score: ${newScore} (${newPassed ? "APROBÓ ✅" : "No aprobó ❌"})`);
    console.log(`  → Feedback: ${gradingResult.overallFeedback}`);

    // 5. Update ONLY this attempt record
    await prisma.evaluationAttempt.update({
      where: { id: attempt.id },
      data: {
        score: newScore,
        passed: newPassed,
        answers: {
          rawAnswers,
          grading: gradingResult,
        },
      },
    });

    console.log(`  ✅ Attempt ${attempt.id} actualizado correctamente.`);
  }

  await prisma.$disconnect();
  console.log("\n✅ Proceso completado.");
}

main().catch(async (err) => {
  console.error("Error inesperado:", err);
  await prisma.$disconnect();
  process.exit(1);
});
